name: Run Python script

on:
  schedule:
    - cron: '0 15-22 * * *'  # запуск каждый час с 12:00 до 19:00 по МСК (с учетом UTC+3)
    - cron: '0 22 * * *'      # запуск в 01:00 по МСК (UTC+3), то есть 22:00 по UTC
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python hh_parser_auto.py
