name: Run Python Script

on:
  schedule:
    # Запуск скрипта в 8:00, 15:00 и 22:00 по МСК
    - cron: '0 8,15,22 * * *'  # Это cron-выражение для запуска каждый день в 8:00, 15:00, 22:00
  workflow_dispatch:  # Позволяет вручную запускать задачу из интерфейса GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest  # Используем последний образ Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Клонируем репозиторий

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Указываем версию Python, которую используем

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt

    - name: Run Python script
      run: python hh_parser_auto.py  # Запуск твоего скрипта
