name: Run Python script

on:
  schedule:
    # Запуск каждый час с 12:00 до 19:00 по МСК.
    # Так как GitHub Actions использует UTC, сдвигаем на -3 часа: 12:00 МСК = 9:00 UTC, 19:00 МСК = 16:00 UTC.
    - cron: '0 9-16 * * *'
    # Дополнительный запуск: в 01:00 по МСК (22:00 UTC)
    - cron: '0 19 * * *'
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Увеличенный таймаут для выполнения задачи

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python hh_parser_auto.py